version: "3.7"
services:
  flask_app:
    build: './flask_app'
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis

  celery_worker:
    build: './worker'
    depends_on:
      - redis

  celery_monitor:
    build: './worker'
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
    #volumes: ['./celery-queue:/queue']

  redis:
    image: 'redis'
    ports:
      - '6379:6379'
 