version: "3.7"
services:
  flask_app:
    build: './flask_app'
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - file-uploads:/flask-app/batch_parsing

  celery_worker:
    build: './worker'
    user: nobody
    depends_on:
      - redis
    volumes:
      - file-uploads:/flask-app/batch_parsing
    

  celery_monitor:
    build: './worker'
    ports:
     - "5555:5555"
    entrypoint: celery 
    command: -A batch_parsing --broker=redis://redis:6379/0 flower --port=5555
    depends_on:
      - redis
    #volumes: ['./celery-queue:/queue']

  redis:
    image: 'redis'
    ports:
      - '6379:6379'


volumes:
  file-uploads:
 