version: "3.7"
services:
  flask_app:
    build: './flask_app'
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - celery_worker

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  celery_worker:
    build: './worker'
    user: nobody
    command: "celery -A batch_parsing worker --loglevel=INFO"
    depends_on:
      - redis
      - flask_app

  flower:  
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888    
    depends_on:
      - redis
      - celery_worker

  monitor:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
    volumes: ['./celery-queue:/queue']
 