version: "3.7"
services:
  flask_app:
    build: './flask_app'
    #restart: always
    ports:
      - "5000:5000"
    volumes:
      - file-uploads:/flask-app/batch_parsing
    command: /usr/local/bin/gunicorn -w 9 -b 0.0.0.0:5000 wsgi:app
    depends_on:
      - redis

  celery_worker:
    build: './worker'
    #user: nobody
    depends_on:
      - redis
    volumes:
      - file-uploads:/flask-app/batch_parsing
    

  celery_monitor:
    build: './worker'
    ports:
     - "5555:5555"
    entrypoint: celery 
    command: -A batch_parsing --broker=redis://redis:6379/0 flower --port=5555
    depends_on:
      - redis
    #volumes: ['./celery-queue:/queue']

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  nginx:
    build: ./nginx
    #container_name: nginx
    #restart: always
    ports:
      - "80:80"
    depends_on:
      - flask_app



volumes:
  file-uploads:
 